import * as FileSystem from 'react-native-fs';
import RNHTMLtoPDF from 'react-native-html-to-pdf';

export const generateInvoicePDF = async (invoiceData: any) => {
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Invoice</title>
      <style>
        body {
          font-family: 'Helvetica', sans-serif;
          padding: 40px;
          background: #fff;
          color: #1e293b;
        }
        .header {
          text-align: center;
          border-bottom: 3px solid #7b2ffc;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header h1 {
          font-size: 28px;
          color: #7b2ffc;
          margin: 0;
        }
        .header p {
          color: #94a3b8;
          font-size: 14px;
        }
        .details {
          display: flex;
          justify-content: space-between;
          margin-bottom: 30px;
        }
        .details .left, .details .right {
          font-size: 14px;
          line-height: 1.8;
        }
        .details .right {
          text-align: right;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
        }
        th {
          background: #7b2ffc;
          color: #fff;
          padding: 12px;
          text-align: left;
          font-size: 13px;
        }
        td {
          padding: 12px;
          border-bottom: 1px solid #e2e8f0;
          font-size: 13px;
        }
        .grand-total {
          font-size: 20px;
          color: #7b2ffc;
          text-align: right;
          margin-top: 20px;
          border-top: 2px solid #7b2ffc;
          padding-top: 15px;
        }
        .footer {
          text-align: center;
          color: #94a3b8;
          font-size: 12px;
          margin-top: 40px;
          border-top: 1px solid #e2e8f0;
          padding-top: 20px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>🧾 TAX INVOICE</h1>
        <p>${invoiceData.invoiceNumber}</p>
      </div>

      <div class="details">
        <div class="left">
          <strong>Bill To:</strong><br/>
          ${invoiceData.customerName || 'Walk-in Customer'}<br/>
          ${invoiceData.customerPhone || ''}<br/>
          ${invoiceData.customerEmail || ''}
        </div>
        <div class="right">
          <strong>Date:</strong> ${new Date(invoiceData.date).toLocaleDateString()}<br/>
          <strong>Status:</strong> ${invoiceData.status.toUpperCase()}
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Item</th>
            <th>Qty</th>
            <th>Rate</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          ${invoiceData.items.map((item: any, index: number) => `
            <tr>
              <td>${index + 1}</td>
              <td>${item.name}</td>
              <td>${item.quantity}</td>
              <td>₹${item.price}</td>
              <td>₹${(item.quantity * item.price).toFixed(0)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div style={{ textAlign: 'right', fontSize: 16, lineHeight: 2 }}>
        <div>Total: ₹${invoiceData.total.toFixed(0)}</div>
        <div>CGST (9%): ₹${invoiceData.cgst.toFixed(0)}</div>
        <div>SGST (9%): ₹${invoiceData.sgst.toFixed(0)}</div>
        <div class="grand-total">Grand Total: ₹${invoiceData.grandTotal.toFixed(0)}</div>
      </div>

      <div class="footer">
        <p>Thank you for your business!</p>
        <p>Generated by My Billing App</p>
      </div>
    </body>
    </html>
  `;

  try {
    const options = {
      html: htmlContent,
      fileName: `Invoice_${invoiceData.invoiceNumber}`,
      directory: 'Documents',
    };

    const pdf = await RNHTMLtoPDF.convert(options);
    return pdf.filePath;
  } catch (error) {
    console.error('PDF generation error:', error);
    throw error;
  }
};
